name: Release Tab Navigator Extension

on:
  push:
    branches: [ main, master ]
    paths:
      - 'manifest.json'
      - 'src/**'
      - 'img/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read current version
      id: version
      run: |
        VERSION=$(grep '"version":' manifest.json | cut -d'"' -f4)
        echo "current=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT

    - name: Check if release exists
      id: check_release
      run: |
        if gh release view ${{ steps.version.outputs.tag }} > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create extension ZIP
      if: steps.check_release.outputs.exists == 'false'
      run: |
        zip -r tab-navigator-v${{ steps.version.outputs.current }}.zip . \
          -x "*.git*" "*.github*" "*node_modules*" "*.md" "AUTO-UPDATE-SETUP.md"

    - name: Create GitHub Release
      if: steps.check_release.outputs.exists == 'false'
      run: |
        gh release create ${{ steps.version.outputs.tag }} \
          --title "v${{ steps.version.outputs.current }}" \
          --notes "v${{ steps.version.outputs.current }}" \
          tab-navigator-v${{ steps.version.outputs.current }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}